apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fullstack-app-client
  description: React frontend application for the fullstack application
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - javascript
    - frontend
    - ui
spec:
  type: website
  lifecycle: production
  owner: team-frontend
  system: fullstack-app
  dependsOn:
    - component:fullstack-app-server
