plugins {
    id 'java'
}

dependencies {
    // Module dependencies
    implementation project(':modules:social:group-api')
    implementation project(':modules:common')
    implementation project(':modules:user:user-impl')
    
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    // Testing - JUnit & Mockito
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
