package com.sportconnect.reference.service;

import lombok.extern.slf4j.Slf4j;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Envelope;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.Point;
import org.locationtech.jts.geom.PrecisionModel;
import org.locationtech.jts.geom.prep.PreparedGeometry;
import org.locationtech.jts.geom.prep.PreparedGeometryFactory;
import org.locationtech.jts.index.strtree.STRtree;
import org.locationtech.jts.io.ParseException;
import org.locationtech.jts.io.WKTReader;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;

/**
 * Offline point-in-polygon and timezone lookup over the boundary data bundled under {@code geo/} (REF-2) —
 * no network call, no IP geolocation. It answers in ISO codes only; turning a code into a seeded, active
 * reference row is {@link ReferenceServiceImpl}'s job.
 *
 * <p>Resources ({@code geo/}, regenerated by {@code reference-impl/geo-data/build-geo-data.mjs}):
 * <ul>
 *   <li>{@code countries.tsv} — {@code iso2 TAB WKT}, Natural Earth admin-0 (1:50m, simplified), all countries</li>
 *   <li>{@code regions-VN.tsv} — {@code iso_3166_2 TAB WKT}, Natural Earth admin-1 (1:10m, simplified), Vietnam only</li>
 *   <li>{@code tz-country.tsv} — {@code IANA zone id TAB iso2}, single-country zones from {@code zone1970.tab}
 *       plus {@code backward} link aliases</li>
 * </ul>
 *
 * <p>Lookup order: a region polygon gives the region and its country (the code prefix, {@code VN-SG} → {@code VN});
 * otherwise a country polygon; otherwise empty. Simplified polygons can put a point within a few km of a border
 * on the wrong side, and offshore points can match nothing — acceptable because the result only pre-fills a form.
 * Coordinates are {@code (longitude, latitude) = (X, Y)}, built with {@code GeometryFactory(new PrecisionModel(), 4326)}.
 *
 * <p>Never throws for a lookup: a coordinate that is NaN or out of range, or a timezone id that is null, blank
 * or unknown, is simply empty.
 *
 * <p><b>Self-managed lazy init, not {@code @Lazy}</b> — the same reasoning as
 * {@code LocationTimeZoneResolver} (LOC-4): building the index is expensive enough that doing it at every Spring
 * context bootstrap caused {@code OutOfMemoryError} across {@code :server:test}'s many context configurations,
 * and {@code @Lazy} did not defer it. The double-checked-locking field defers the cost to the first lookup no
 * matter how the bean is wired.
 */
@Slf4j
@Component
public class GeoBoundaryResolver {

    /** Where a point falls. {@code regionIsoCode} is {@code null} when only a country polygon matched. */
    public record Hit(String countryIso2, String regionIsoCode) {
    }

    private static final String COUNTRIES = "geo/countries.tsv";
    private static final String REGIONS_VN = "geo/regions-VN.tsv";
    private static final String TIME_ZONES = "geo/tz-country.tsv";

    private volatile Index index;

    /**
     * Finds the region (Vietnam only) and country containing a coordinate. Region polygons are tried first, then
     * country polygons; empty when neither contains the point or the coordinate is not a valid WGS 84 position.
     */
    public Optional<Hit> locate(double latitude, double longitude) {
        if (!isValidCoordinate(latitude, longitude)) {
            return Optional.empty();
        }
        Index idx = index();
        Point point = idx.factory.createPoint(new Coordinate(longitude, latitude));

        String regionCode = idx.regions.firstCovering(point);
        if (regionCode != null) {
            return Optional.of(new Hit(regionCode.substring(0, 2), regionCode));
        }
        String countryCode = idx.countries.firstCovering(point);
        return countryCode == null ? Optional.empty() : Optional.of(new Hit(countryCode, null));
    }

    /**
     * The ISO 3166-1 alpha-2 country of an IANA zone id, only when that zone belongs to exactly one country. A zone
     * shared by several countries (e.g. {@code Asia/Bangkok}), an {@code Etc/*} or {@code UTC} zone, an unknown id,
     * or a null/blank one is empty — a shared zone must not be used to guess a country.
     */
    public Optional<String> countryForTimeZone(String timeZoneId) {
        if (timeZoneId == null || timeZoneId.isBlank()) {
            return Optional.empty();
        }
        return Optional.ofNullable(index().timeZones.get(timeZoneId.trim()));
    }

    /** ISO alpha-2 codes that have a country polygon. Exposed for the "every seeded country has a polygon" invariant test. */
    public Set<String> countryCodes() {
        return index().countries.codes();
    }

    /** ISO 3166-2 codes that have a region polygon. Exposed for the "seed and polygons match 1:1" invariant test. */
    public Set<String> regionCodes() {
        return index().regions.codes();
    }

    private static boolean isValidCoordinate(double latitude, double longitude) {
        return latitude >= -90.0 && latitude <= 90.0 && longitude >= -180.0 && longitude <= 180.0;
    }

    private Index index() {
        Index result = index;
        if (result == null) {
            synchronized (this) {
                result = index;
                if (result == null) {
                    index = result = Index.load();
                }
            }
        }
        return result;
    }

    /** Immutable, fully built lookup structures. */
    private static final class Index {
        final GeometryFactory factory;
        final Polygons countries;
        final Polygons regions;
        final Map<String, String> timeZones;

        private Index(Polygons countries, Polygons regions, Map<String, String> timeZones, GeometryFactory factory) {
            this.countries = countries;
            this.regions = regions;
            this.timeZones = timeZones;
            this.factory = factory;
        }

        static Index load() {
            long started = System.nanoTime();
            GeometryFactory factory = new GeometryFactory(new PrecisionModel(), 4326);
            WKTReader reader = new WKTReader(factory);
            Polygons countries = Polygons.load(COUNTRIES, reader);
            Polygons regions = Polygons.load(REGIONS_VN, reader);
            Map<String, String> timeZones = loadTimeZones();
            log.info("GeoBoundaryResolver index built: {} countries, {} regions, {} timezones in {} ms",
                    countries.codes().size(), regions.codes().size(), timeZones.size(),
                    (System.nanoTime() - started) / 1_000_000);
            return new Index(countries, regions, timeZones, factory);
        }

        private static Map<String, String> loadTimeZones() {
            Map<String, String> zones = new HashMap<>();
            for (String[] row : readTsv(TIME_ZONES)) {
                zones.put(row[0], row[1]);
            }
            return Map.copyOf(zones);
        }
    }

    /** A code → polygon collection behind an {@link STRtree}. */
    private static final class Polygons {
        private final STRtree tree = new STRtree();
        private final Set<String> codes = new TreeSet<>();

        static Polygons load(String resource, WKTReader reader) {
            Polygons polygons = new Polygons();
            for (String[] row : readTsv(resource)) {
                Geometry geometry;
                try {
                    geometry = reader.read(row[1]);
                } catch (ParseException e) {
                    throw new IllegalStateException("Unparseable geometry for " + row[0] + " in " + resource, e);
                }
                if (!geometry.isValid()) {
                    log.warn("Invalid geometry for {} in {} — repairing with buffer(0)", row[0], resource);
                    geometry = geometry.buffer(0);
                }
                polygons.codes.add(row[0]);
                polygons.tree.insert(geometry.getEnvelopeInternal(),
                        new Entry(row[0], PreparedGeometryFactory.prepare(geometry)));
            }
            polygons.tree.build();
            return polygons;
        }

        String firstCovering(Point point) {
            Envelope probe = new Envelope(point.getCoordinate());
            for (Object candidate : tree.query(probe)) {
                Entry entry = (Entry) candidate;
                if (entry.geometry.covers(point)) {
                    return entry.code;
                }
            }
            return null;
        }

        Set<String> codes() {
            return Collections.unmodifiableSet(codes);
        }

        private record Entry(String code, PreparedGeometry geometry) {
        }
    }

    /** Reads a two-column, tab-separated classpath resource; blank lines are skipped. */
    private static List<String[]> readTsv(String resource) {
        List<String[]> rows = new ArrayList<>();
        try (InputStream in = GeoBoundaryResolver.class.getClassLoader().getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("Missing classpath resource: " + resource);
            }
            BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) {
                    continue;
                }
                String[] cols = line.split("\t", 2);
                if (cols.length != 2) {
                    throw new IllegalStateException("Malformed line in " + resource);
                }
                rows.add(cols);
            }
        } catch (IOException e) {
            throw new IllegalStateException("Cannot read classpath resource: " + resource, e);
        }
        return rows;
    }
}
