package com.sportconnect.session.api.dto;

/**
 * {@code GROUP_RECURRING} = any session with a non-null groupId (manually created by an
 * owner/admin, or auto-generated by the recurrence job). {@code STANDALONE} = groupId is null.
 * {@code TOURNAMENT}/{@code TRAINING} are reserved for a future round — no supporting logic
 * exists for them yet, they exist here only so adding them later doesn't require a schema change.
 */
public enum SessionType {
    GROUP_RECURRING,
    STANDALONE,
    TOURNAMENT,
    TRAINING
}
