-- SESSION-1: Scheduled sports activities. groupId null = standalone; non-null = linked to a
-- group (manually created by an owner/admin, or later auto-generated by the recurrence job).
-- Always references a shared Location (LOC-1, V030) rather than carrying raw location fields.

CREATE TABLE sessions (
    id BIGSERIAL PRIMARY KEY,
    group_id BIGINT,
    session_type VARCHAR(30) NOT NULL,
    created_by UUID NOT NULL REFERENCES users(id),
    sport_id BIGINT,
    title VARCHAR(200),
    description TEXT,
    location_id BIGINT NOT NULL REFERENCES locations(id),
    scheduled_start TIMESTAMP NOT NULL,
    scheduled_end_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_group_session_start UNIQUE (group_id, scheduled_start)
);

COMMENT ON TABLE sessions IS 'Scheduled sports activities, group-linked or standalone (SESSION-1)';
COMMENT ON COLUMN sessions.group_id IS 'Null = standalone session, created directly by a user';
COMMENT ON COLUMN sessions.session_type IS 'GROUP_RECURRING or STANDALONE today; TOURNAMENT/TRAINING reserved for a future round';
COMMENT ON COLUMN sessions.location_id IS 'Always references the shared locations table (LOC-1) — no raw location fields on this table';

CREATE INDEX idx_sessions_group_id ON sessions(group_id);
CREATE INDEX idx_sessions_created_by ON sessions(created_by);
CREATE INDEX idx_sessions_status_scheduled_start ON sessions(status, scheduled_start);
CREATE INDEX idx_sessions_location_id ON sessions(location_id);
